iname: Hub image

on:
  push:
    tags:
      - hub-*

jobs:
  build:
    name: Build & push Docker image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install Cosign
        uses: sigstore/cosign-installer@v3.1.2
      - name: Log in to conta.in.rs registry
        uses: docker/login-action@v3
        with:
          registry: conta.in.rs
          username: ${{ secrets.HARBOR_USERNAME }}
          password: ${{ secrets.HARBOR_PASSWORD }}
      - name: Get tags
        uses: docker/metadata-action@v5
        id: get-metadata
        with:
          images: |
            conta.in.rs/jupyterhub/k8s-hub
          flavor: |
            latest=false
          tags: |
            type=match,pattern=hub-(.*),group=1
      - name: Build & push image to registry
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: "{{defaultContext}}:hub"
          push: true
          build-args: |
            VERSION=${{ steps.get-metadata.outputs.version }}
          tags: ${{ steps.get-metadata.outputs.tags }} 
      - name: Sign image
        run: |
          IFS=$'\n'
          for TAG in $TAGS
          do
            cosign sign --yes "${TAG}@${DIGEST}"
          done
        env:
          TAGS: ${{ steps.get-metadata.outputs.tags }}
          DIGEST: ${{ steps.build-and-push.outputs.digest }}
